version: '3'
services:
  app:
    env_file:
      - .env
    container_name: nestjs-core
    restart: always
    build: .
    ports:
      - '$PORT:$PORT'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
